   service: scrape

   package:
     individually: true

   provider:
     name: aws
     runtime: nodejs18.x
     region: us-west-1
     iamRoleStatements:
       - Effect: Allow
         Action:
           - s3:PutObject
         Resource: arn:aws:s3:::storage/*

   resources:
     Resources:
       ScrapedJobObjectsBucket:
         Type: AWS::S3::Bucket
         Properties:
           BucketName: scraped-job-objects  

   functions:
     entry-level-jobs:
       handler: index.handler
       timeout: 900
       memorySize: 10240
       layers:
         - !Ref ChromiumbinLambdaLayer
       package:
          patterns:
            - '!layer/**'
            - 'mappings/**'
            - 'scrapers/**'
            - 'utils/**'
       events:
         - schedule: cron(0 14 ? * MON *)

   layers:
     chromiumbin:
       package:
          artifact: layer/chromium-v116.0.0-layer.zip

   plugins:
     - serverless-dotenv-plugin
     - serverless-offline
