require("dotenv").config();

const Constants = {
	JobCategoriesMap: {
		"Biz Dev": {
			keywords: [
				"business",
				"entrepreneur",
				"sales",
				"partnerships",
				"strategy",
				"growth",
				"client",
				"mba",
				"customer",
				"relations",
				"sdr",
			],
			phrases: ["account executive", "account manager", "account management"],
		},
		Design: {
			keywords: [
				"design",
				"graphic",
				"ui",
				"ux",
				"art",
				"artist",
				"visual",
				"creative",
				"illustration",
				"branding",
				"photoshop",
				"figma",
				"sketch",
			],
			phrases: ["user interface", "user experience"],
		},
		Engineering: {
			keywords: [
				"engineer",
				"engineering",
				"developer",
				"database",
				"robotics",
				"hardware",
				"programmer",
				"software",
				"frontend",
				"backend",
				"fullstack",
				"java",
				"python",
				"javascript",
				"c++",
				"ruby",
				"php",
				"ios",
				"android",
				"devops",
				"cloud",
				"aws",
				"azure",
				"it",
				"mechatronics",
				"computational",
				"compilers",
				"devops",
				"mlops",
				"compilers",
				"gcp",
				"trading",
				"cybersecurity",
				"trader",
			],
			phrases: [
				"software engineer",
				"electrical engineer",
				"cyber security",
				"full stack",
				"information technology",
				"solutions architect",
				"launch internship", // citadel calls their eng internships this
				"open source",
				"computer vision",
				"deep learning",
				"machine learning",
			],
		},
		Finance: {
			keywords: [
				"finance",
				"analyst",
				"accounting",
				"accountant",
				"financial",
				"budget",
				"tax",
				"audit",
				"treasury",
				"revenue",
				"investment",
				"actuarial",
				"equity",
				"controller",
				"debt",
				"risk",
				"compliance",
			],
			phrases: ["financial analyst", "market analysis"],
		},
		Legal: {
			keywords: [
				"legal",
				"law",
				"compliance",
				"regulatory",
				"counsel",
				"litigation",
				"corporate",
				"attorney",
				"solicitor",
				"paralegal",
			],
			phrases: [
				"legal counsel",
				"legal analyst",
				"legal assistant",
				"intellectual property",
			],
		},
		Marketing: {
			keywords: [
				"marketing",
				"seo",
				"social media",
				"content",
				"brand",
				"advertising",
				"copywriter",
				"email",
				"crm",
				"analytics",
				"ppc",
				"sem",
			],
			phrases: [],
		},
		Operations: {
			keywords: [
				"operations",
				"logistics",
				"facilities",
				"fulfillment",
				"admin",
				"receptionist",
				"workplace",
				"purchasing",
				"coordinator",
				"procurement",
				"inventory",
				"production",
				"manufacturing",
				"operating",
				"process",
				"assistant",
				"ceo's",
			],
			phrases: ["right hand", "supply chain", "founder office"],
		},
		PR: {
			keywords: [
				"pr",
				"communications",
				"communication",
				"translation",
				"media",
				"press",
				"journalism",
				"journalist",
				"events",
				"community",
				"english",
			],
			phrases: ["public relations"],
		},
		Product: {
			keywords: [
				"product",
				"project",
				"owner",
				"po",
				"pm",
				"roadmap",
				"scrum",
				"agile",
			],
			phrases: ["product manager", "product owner", "product management"],
		},
		Research: {
			keywords: [
				"research",
				"researcher",
				"data",
				"statistics",
				"science",
				"study",
				"survey",
			],
			phrases: [],
		},
		VC: {
			keywords: [
				"venture",
				"capital",
				"vc",
				"investment",
				"fund",
				"equity",
				"investor",
				"startup",
				"angel",
				"portfolio",
			],
			phrases: [],
		},
		HR: {
			keywords: [
				"hr",
				"hrbp",
				"recruiting",
				"recruitment",
				"talent",
				"benefits",
				"payroll",
				"training",
			],
			phrases: ["human resources", "talent acquisition", "employee relations"],
		},
	},
	Pallet: {
		JobsApiEndpoint: "https://gen-z-vcs-jobs.pallet.com/api/v1/graphql",
		ConstructJobLink: (listingUuid) =>
			`https://gen-z-vcs-jobs.pallet.com/jobs/${listingUuid}`,
	},
	YComb: {
		LoginUrl:
			"https://account.ycombinator.com/?continue=https%3A%2F%2Fwww.workatastartup.com%2F",
		InternshipsUrl:
			"https://www.workatastartup.com/companies?demographic=any&hasEquity=any&hasSalary=any&industry=any&interviewProcess=any&jobType=intern&layout=list-compact&sortBy=created_desc&tab=any&usVisaNotRequired=any",
	},
	TrueUp: {
		HomeUrl: "https://www.trueup.io/",
	},
	Delays: {
		Short: 1000,
		Medium: 3000,
		Long: 6000,
	},
	WideViewportDimensions: {
		width: 1920,
		height: 1080,
	},
	Credentials: {
		Username: process.env.UNISTART_USERNAME,
		Password: process.env.UNISTART_PASSWORD,
	},
};

module.exports = Constants;